// Code generated by MockGen. DO NOT EDIT.
// Source: ../../auth/token_service.go

// Package auth is a generated GoMock package.
package auth

import (
	context "context"
	reflect "reflect"
	time "time"

	gomock "github.com/golang/mock/gomock"
)

// MockTokenServiceInterface is a mock of TokenServiceInterface interface.
type MockTokenServiceInterface struct {
	ctrl     *gomock.Controller
	recorder *MockTokenServiceInterfaceMockRecorder
}

// MockTokenServiceInterfaceMockRecorder is the mock recorder for MockTokenServiceInterface.
type MockTokenServiceInterfaceMockRecorder struct {
	mock *MockTokenServiceInterface
}

// NewMockTokenServiceInterface creates a new mock instance.
func NewMockTokenServiceInterface(ctrl *gomock.Controller) *MockTokenServiceInterface {
	mock := &MockTokenServiceInterface{ctrl: ctrl}
	mock.recorder = &MockTokenServiceInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTokenServiceInterface) EXPECT() *MockTokenServiceInterfaceMockRecorder {
	return m.recorder
}

// InvalidateAllUserTokens mocks base method.
func (m *MockTokenServiceInterface) InvalidateAllUserTokens(ctx context.Context, userID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InvalidateAllUserTokens", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// InvalidateAllUserTokens indicates an expected call of InvalidateAllUserTokens.
func (mr *MockTokenServiceInterfaceMockRecorder) InvalidateAllUserTokens(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InvalidateAllUserTokens", reflect.TypeOf((*MockTokenServiceInterface)(nil).InvalidateAllUserTokens), ctx, userID)
}

// InvalidateToken mocks base method.
func (m *MockTokenServiceInterface) InvalidateToken(ctx context.Context, jti string, ttl time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InvalidateToken", ctx, jti, ttl)
	ret0, _ := ret[0].(error)
	return ret0
}

// InvalidateToken indicates an expected call of InvalidateToken.
func (mr *MockTokenServiceInterfaceMockRecorder) InvalidateToken(ctx, jti, ttl interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InvalidateToken", reflect.TypeOf((*MockTokenServiceInterface)(nil).InvalidateToken), ctx, jti, ttl)
}

// IsTokenBlacklisted mocks base method.
func (m *MockTokenServiceInterface) IsTokenBlacklisted(ctx context.Context, jti string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsTokenBlacklisted", ctx, jti)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsTokenBlacklisted indicates an expected call of IsTokenBlacklisted.
func (mr *MockTokenServiceInterfaceMockRecorder) IsTokenBlacklisted(ctx, jti interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsTokenBlacklisted", reflect.TypeOf((*MockTokenServiceInterface)(nil).IsTokenBlacklisted), ctx, jti)
}

// IsUserValid mocks base method.
func (m *MockTokenServiceInterface) IsUserValid(ctx context.Context, userID string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsUserValid", ctx, userID)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsUserValid indicates an expected call of IsUserValid.
func (mr *MockTokenServiceInterfaceMockRecorder) IsUserValid(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsUserValid", reflect.TypeOf((*MockTokenServiceInterface)(nil).IsUserValid), ctx, userID)
}
