/**
 * Defines standardized error codes that can be returned from the API.
 * This allows the frontend to handle specific errors programmatically
 * without relying on parsing error message strings.
 * This enum should be kept in sync with the backend's apperror package.
 */
export const enum ApiErrorCode {
    // --- Generic Errors ---
    INTERNAL_ERROR = "INTERNAL_ERROR",
    BAD_REQUEST = "BAD_REQUEST",
    VALIDATION_ERROR = "VALIDATION_ERROR", // Kept for general client-side validation
    SERVICE_UNAVAILABLE = "SERVICE_UNAVAILABLE",
    NO_FIELDS_TO_UPDATE = "NO_FIELDS_TO_UPDATE",
    INVALID_ID = "INVALID_ID",
    PAGINATION_INVALID = "PAGINATION_INVALID",
    FORBIDDEN = "FORBIDDEN",

    // --- Auth & Token Errors ---
    INVALID_CREDENTIALS = "INVALID_CREDENTIALS",
    INVALID_TOKEN = "INVALID_TOKEN",
    TOKEN_EXPIRED = "TOKEN_EXPIRED", // Note: Backend might use INVALID_TOKEN for this
    INVALID_CLAIMS = "INVALID_CLAIMS",
    INVALID_ISSUER = "INVALID_ISSUER",
    INVALID_AUDIENCE = "INVALID_AUDIENCE",
    TOKEN_INVALIDATED = "TOKEN_INVALIDATED",
    LOGIN_METHOD_MISMATCH = "LOGIN_METHOD_MISMATCH",

    // --- Verification & OTP Errors ---
    EMAIL_NOT_VERIFIED = "EMAIL_NOT_VERIFIED",
    EMAIL_ALREADY_VERIFIED = "EMAIL_ALREADY_VERIFIED",
    INVALID_OTP = "INVALID_OTP",
    OTP_EXPIRED = "OTP_EXPIRED",
    VERIFICATION_TOKEN_INVALID = "VERIFICATION_TOKEN_INVALID", // Kept for frontend logic

    // --- User & Profile Errors ---
    USER_NOT_FOUND = "USER_NOT_FOUND",
    USERNAME_EXISTS = "USERNAME_EXISTS",
    EMAIL_EXISTS = "EMAIL_EXISTS",
    USER_INACTIVE = "USER_INACTIVE",
    INVALID_GENDER = "INVALID_GENDER",
    INVALID_DATE_FORMAT = "INVALID_DATE_FORMAT",
    AGE_TOO_YOUNG = "AGE_TOO_YOUNG",
    INVALID_BIRTH_DATE = "INVALID_BIRTH_DATE",
    INVALID_PROVINCE = "INVALID_PROVINCE",
    TOO_MANY_INTERESTS = "TOO_MANY_INTERESTS",
    INVALID_INTEREST = "INVALID_INTEREST",

    // --- Community & Membership Errors ---
    COMMUNITY_NOT_FOUND = "COMMUNITY_NOT_FOUND",
    COMMUNITY_NAME_EXISTS = "COMMUNITY_NAME_EXISTS",
    COMMUNITY_DELETED = "COMMUNITY_DELETED",
    USER_NOT_MEMBER = "USER_NOT_MEMBER",
    MEMBERSHIP_NOT_FOUND = "MEMBERSHIP_NOT_FOUND",
    ALREADY_MEMBER = "ALREADY_MEMBER",
    MEMBERSHIP_CREATE_FAILED = "MEMBERSHIP_CREATE_FAILED",
    MEMBERSHIP_DELETE_FAILED = "MEMBERSHIP_DELETE_FAILED",
    INVALID_MEMBERSHIP_DATA = "INVALID_MEMBERSHIP_DATA",

    // --- Post, Vote, Poll Errors ---
    POST_NOT_FOUND = "POST_NOT_FOUND",
    VOTE_NOT_FOUND = "VOTE_NOT_FOUND",
    POLL_ALREADY_VOTED = "POLL_ALREADY_VOTED",
    POLL_CANNOT_EDIT = "POLL_CANNOT_EDIT",

    // --- Comment Errors ---
    COMMENT_NOT_FOUND = "COMMENT_NOT_FOUND",
    DEPTH_TOO_HIGH = "DEPTH_TOO_HIGH",

    // --- Messaging Errors ---
    CHANNEL_NOT_FOUND = "CHANNEL_NOT_FOUND",
    NO_MESSAGE_FOUND = "NO_MESSAGE_FOUND",
}
