// Code generated by MockGen. DO NOT EDIT.
// Source: ../../repo/post_repo.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	model "github.com/giakiet05/lkforum/internal/model"
	repo "github.com/giakiet05/lkforum/internal/repo"
	gomock "github.com/golang/mock/gomock"
)

// MockPostRepo is a mock of PostRepo interface.
type MockPostRepo struct {
	ctrl     *gomock.Controller
	recorder *MockPostRepoMockRecorder
}

// MockPostRepoMockRecorder is the mock recorder for MockPostRepo.
type MockPostRepoMockRecorder struct {
	mock *MockPostRepo
}

// NewMockPostRepo creates a new mock instance.
func NewMockPostRepo(ctrl *gomock.Controller) *MockPostRepo {
	mock := &MockPostRepo{ctrl: ctrl}
	mock.recorder = &MockPostRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPostRepo) EXPECT() *MockPostRepoMockRecorder {
	return m.recorder
}

// BanPost mocks base method.
func (m *MockPostRepo) BanPost(ctx context.Context, postID string, reason *string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BanPost", ctx, postID, reason)
	ret0, _ := ret[0].(error)
	return ret0
}

// BanPost indicates an expected call of BanPost.
func (mr *MockPostRepoMockRecorder) BanPost(ctx, postID, reason interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BanPost", reflect.TypeOf((*MockPostRepo)(nil).BanPost), ctx, postID, reason)
}

// CountCreatedAfter mocks base method.
func (m *MockPostRepo) CountCreatedAfter(ctx context.Context, since time.Time) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountCreatedAfter", ctx, since)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountCreatedAfter indicates an expected call of CountCreatedAfter.
func (mr *MockPostRepoMockRecorder) CountCreatedAfter(ctx, since interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountCreatedAfter", reflect.TypeOf((*MockPostRepo)(nil).CountCreatedAfter), ctx, since)
}

// CountPendingApproval mocks base method.
func (m *MockPostRepo) CountPendingApproval(ctx context.Context) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountPendingApproval", ctx)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountPendingApproval indicates an expected call of CountPendingApproval.
func (mr *MockPostRepoMockRecorder) CountPendingApproval(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountPendingApproval", reflect.TypeOf((*MockPostRepo)(nil).CountPendingApproval), ctx)
}

// CountTotal mocks base method.
func (m *MockPostRepo) CountTotal(ctx context.Context) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountTotal", ctx)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountTotal indicates an expected call of CountTotal.
func (mr *MockPostRepoMockRecorder) CountTotal(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountTotal", reflect.TypeOf((*MockPostRepo)(nil).CountTotal), ctx)
}

// Create mocks base method.
func (m *MockPostRepo) Create(ctx context.Context, post *model.Post) (*model.Post, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, post)
	ret0, _ := ret[0].(*model.Post)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockPostRepoMockRecorder) Create(ctx, post interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockPostRepo)(nil).Create), ctx, post)
}

// Delete mocks base method.
func (m *MockPostRepo) Delete(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockPostRepoMockRecorder) Delete(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockPostRepo)(nil).Delete), ctx, id)
}

// Find mocks base method.
func (m *MockPostRepo) Find(ctx context.Context, filter repo.Filter, opts *repo.FindOptions) ([]*model.Post, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", ctx, filter, opts)
	ret0, _ := ret[0].([]*model.Post)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Find indicates an expected call of Find.
func (mr *MockPostRepoMockRecorder) Find(ctx, filter, opts interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockPostRepo)(nil).Find), ctx, filter, opts)
}

// GetBannedPosts mocks base method.
func (m *MockPostRepo) GetBannedPosts(ctx context.Context, communityID string, page, pageSize int) ([]*model.Post, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBannedPosts", ctx, communityID, page, pageSize)
	ret0, _ := ret[0].([]*model.Post)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetBannedPosts indicates an expected call of GetBannedPosts.
func (mr *MockPostRepoMockRecorder) GetBannedPosts(ctx, communityID, page, pageSize interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBannedPosts", reflect.TypeOf((*MockPostRepo)(nil).GetBannedPosts), ctx, communityID, page, pageSize)
}

// GetByID mocks base method.
func (m *MockPostRepo) GetByID(ctx context.Context, id string) (*model.Post, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*model.Post)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockPostRepoMockRecorder) GetByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockPostRepo)(nil).GetByID), ctx, id)
}

// GetByIDs mocks base method.
func (m *MockPostRepo) GetByIDs(ctx context.Context, ids []string) ([]*model.Post, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByIDs", ctx, ids)
	ret0, _ := ret[0].([]*model.Post)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByIDs indicates an expected call of GetByIDs.
func (mr *MockPostRepoMockRecorder) GetByIDs(ctx, ids interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByIDs", reflect.TypeOf((*MockPostRepo)(nil).GetByIDs), ctx, ids)
}

// Increment mocks base method.
func (m *MockPostRepo) Increment(ctx context.Context, id, field string, value int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Increment", ctx, id, field, value)
	ret0, _ := ret[0].(error)
	return ret0
}

// Increment indicates an expected call of Increment.
func (mr *MockPostRepoMockRecorder) Increment(ctx, id, field, value interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Increment", reflect.TypeOf((*MockPostRepo)(nil).Increment), ctx, id, field, value)
}

// SoftDelete mocks base method.
func (m *MockPostRepo) SoftDelete(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SoftDelete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// SoftDelete indicates an expected call of SoftDelete.
func (mr *MockPostRepoMockRecorder) SoftDelete(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SoftDelete", reflect.TypeOf((*MockPostRepo)(nil).SoftDelete), ctx, id)
}

// UnbanPost mocks base method.
func (m *MockPostRepo) UnbanPost(ctx context.Context, postID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnbanPost", ctx, postID)
	ret0, _ := ret[0].(error)
	return ret0
}

// UnbanPost indicates an expected call of UnbanPost.
func (mr *MockPostRepoMockRecorder) UnbanPost(ctx, postID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnbanPost", reflect.TypeOf((*MockPostRepo)(nil).UnbanPost), ctx, postID)
}

// Update mocks base method.
func (m *MockPostRepo) Update(ctx context.Context, filter repo.Filter, update repo.UpdateDocument) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, filter, update)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockPostRepoMockRecorder) Update(ctx, filter, update interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockPostRepo)(nil).Update), ctx, filter, update)
}

// UpdateByID mocks base method.
func (m *MockPostRepo) UpdateByID(ctx context.Context, id string, update repo.UpdateDocument) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateByID", ctx, id, update)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateByID indicates an expected call of UpdateByID.
func (mr *MockPostRepoMockRecorder) UpdateByID(ctx, id, update interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateByID", reflect.TypeOf((*MockPostRepo)(nil).UpdateByID), ctx, id, update)
}
