// Code generated by MockGen. DO NOT EDIT.
// Source: ../../repo/message_repo.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	model "github.com/giakiet05/lkforum/internal/model"
	gomock "github.com/golang/mock/gomock"
)

// MockMessageRepo is a mock of MessageRepo interface.
type MockMessageRepo struct {
	ctrl     *gomock.Controller
	recorder *MockMessageRepoMockRecorder
}

// MockMessageRepoMockRecorder is the mock recorder for MockMessageRepo.
type MockMessageRepoMockRecorder struct {
	mock *MockMessageRepo
}

// NewMockMessageRepo creates a new mock instance.
func NewMockMessageRepo(ctrl *gomock.Controller) *MockMessageRepo {
	mock := &MockMessageRepo{ctrl: ctrl}
	mock.recorder = &MockMessageRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMessageRepo) EXPECT() *MockMessageRepoMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockMessageRepo) Create(ctx context.Context, message *model.Message) (*model.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, message)
	ret0, _ := ret[0].(*model.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockMessageRepoMockRecorder) Create(ctx, message interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockMessageRepo)(nil).Create), ctx, message)
}

// Delete mocks base method.
func (m *MockMessageRepo) Delete(ctx context.Context, messageID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, messageID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockMessageRepoMockRecorder) Delete(ctx, messageID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockMessageRepo)(nil).Delete), ctx, messageID)
}

// GetByID mocks base method.
func (m *MockMessageRepo) GetByID(ctx context.Context, messageID string) (*model.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, messageID)
	ret0, _ := ret[0].(*model.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockMessageRepoMockRecorder) GetByID(ctx, messageID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockMessageRepo)(nil).GetByID), ctx, messageID)
}

// GetFilter mocks base method.
func (m *MockMessageRepo) GetFilter(ctx context.Context, channelID string, senderID, searchContent *string, isRead, isSent, isMedia *bool, page, pageSize int) ([]model.Message, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFilter", ctx, channelID, senderID, searchContent, isRead, isSent, isMedia, page, pageSize)
	ret0, _ := ret[0].([]model.Message)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetFilter indicates an expected call of GetFilter.
func (mr *MockMessageRepoMockRecorder) GetFilter(ctx, channelID, senderID, searchContent, isRead, isSent, isMedia, page, pageSize interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFilter", reflect.TypeOf((*MockMessageRepo)(nil).GetFilter), ctx, channelID, senderID, searchContent, isRead, isSent, isMedia, page, pageSize)
}

// IsSendByUser mocks base method.
func (m *MockMessageRepo) IsSendByUser(ctx context.Context, messageID, userID string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsSendByUser", ctx, messageID, userID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsSendByUser indicates an expected call of IsSendByUser.
func (mr *MockMessageRepoMockRecorder) IsSendByUser(ctx, messageID, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsSendByUser", reflect.TypeOf((*MockMessageRepo)(nil).IsSendByUser), ctx, messageID, userID)
}
