// Code generated by MockGen. DO NOT EDIT.
// Source: ../../repo/report_repo.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	model "github.com/giakiet05/lkforum/internal/model"
	gomock "github.com/golang/mock/gomock"
)

// MockReportRepo is a mock of ReportRepo interface.
type MockReportRepo struct {
	ctrl     *gomock.Controller
	recorder *MockReportRepoMockRecorder
}

// MockReportRepoMockRecorder is the mock recorder for MockReportRepo.
type MockReportRepoMockRecorder struct {
	mock *MockReportRepo
}

// NewMockReportRepo creates a new mock instance.
func NewMockReportRepo(ctrl *gomock.Controller) *MockReportRepo {
	mock := &MockReportRepo{ctrl: ctrl}
	mock.recorder = &MockReportRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReportRepo) EXPECT() *MockReportRepoMockRecorder {
	return m.recorder
}

// CountCreatedAfter mocks base method.
func (m *MockReportRepo) CountCreatedAfter(ctx context.Context, since time.Time) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountCreatedAfter", ctx, since)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountCreatedAfter indicates an expected call of CountCreatedAfter.
func (mr *MockReportRepoMockRecorder) CountCreatedAfter(ctx, since interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountCreatedAfter", reflect.TypeOf((*MockReportRepo)(nil).CountCreatedAfter), ctx, since)
}

// CountPending mocks base method.
func (m *MockReportRepo) CountPending(ctx context.Context) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountPending", ctx)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountPending indicates an expected call of CountPending.
func (mr *MockReportRepoMockRecorder) CountPending(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountPending", reflect.TypeOf((*MockReportRepo)(nil).CountPending), ctx)
}

// Create mocks base method.
func (m *MockReportRepo) Create(ctx context.Context, report *model.Report) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, report)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockReportRepoMockRecorder) Create(ctx, report interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockReportRepo)(nil).Create), ctx, report)
}

// Delete mocks base method.
func (m *MockReportRepo) Delete(ctx context.Context, reportID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, reportID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockReportRepoMockRecorder) Delete(ctx, reportID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockReportRepo)(nil).Delete), ctx, reportID)
}

// DeleteBatch mocks base method.
func (m *MockReportRepo) DeleteBatch(ctx context.Context, reportIDs []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteBatch", ctx, reportIDs)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteBatch indicates an expected call of DeleteBatch.
func (mr *MockReportRepoMockRecorder) DeleteBatch(ctx, reportIDs interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteBatch", reflect.TypeOf((*MockReportRepo)(nil).DeleteBatch), ctx, reportIDs)
}

// GetByID mocks base method.
func (m *MockReportRepo) GetByID(ctx context.Context, id string) (*model.Report, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*model.Report)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockReportRepoMockRecorder) GetByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockReportRepo)(nil).GetByID), ctx, id)
}

// GetFilter mocks base method.
func (m *MockReportRepo) GetFilter(ctx context.Context, reporterID, targetID *string, targetType model.ReportTargetType, reason *string, startDate, endDate *time.Time, page, pageSize int) ([]model.Report, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFilter", ctx, reporterID, targetID, targetType, reason, startDate, endDate, page, pageSize)
	ret0, _ := ret[0].([]model.Report)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetFilter indicates an expected call of GetFilter.
func (mr *MockReportRepoMockRecorder) GetFilter(ctx, reporterID, targetID, targetType, reason, startDate, endDate, page, pageSize interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFilter", reflect.TypeOf((*MockReportRepo)(nil).GetFilter), ctx, reporterID, targetID, targetType, reason, startDate, endDate, page, pageSize)
}

// IsReporter mocks base method.
func (m *MockReportRepo) IsReporter(ctx context.Context, userID, reportID string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsReporter", ctx, userID, reportID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsReporter indicates an expected call of IsReporter.
func (mr *MockReportRepoMockRecorder) IsReporter(ctx, userID, reportID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsReporter", reflect.TypeOf((*MockReportRepo)(nil).IsReporter), ctx, userID, reportID)
}

// IsReporterOfAllReports mocks base method.
func (m *MockReportRepo) IsReporterOfAllReports(ctx context.Context, userID string, reportIDs []string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsReporterOfAllReports", ctx, userID, reportIDs)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsReporterOfAllReports indicates an expected call of IsReporterOfAllReports.
func (mr *MockReportRepoMockRecorder) IsReporterOfAllReports(ctx, userID, reportIDs interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsReporterOfAllReports", reflect.TypeOf((*MockReportRepo)(nil).IsReporterOfAllReports), ctx, userID, reportIDs)
}
