// Code generated by MockGen. DO NOT EDIT.
// Source: ../../repo/vote_repo.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	model "github.com/giakiet05/lkforum/internal/model"
	gomock "github.com/golang/mock/gomock"
)

// MockVoteRepo is a mock of VoteRepo interface.
type MockVoteRepo struct {
	ctrl     *gomock.Controller
	recorder *MockVoteRepoMockRecorder
}

// MockVoteRepoMockRecorder is the mock recorder for MockVoteRepo.
type MockVoteRepoMockRecorder struct {
	mock *MockVoteRepo
}

// NewMockVoteRepo creates a new mock instance.
func NewMockVoteRepo(ctrl *gomock.Controller) *MockVoteRepo {
	mock := &MockVoteRepo{ctrl: ctrl}
	mock.recorder = &MockVoteRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVoteRepo) EXPECT() *MockVoteRepoMockRecorder {
	return m.recorder
}

// FindUserVotes mocks base method.
func (m *MockVoteRepo) FindUserVotes(ctx context.Context, userID string, targetIDs []string, targetType model.VoteTargetType) (map[string]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindUserVotes", ctx, userID, targetIDs, targetType)
	ret0, _ := ret[0].(map[string]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindUserVotes indicates an expected call of FindUserVotes.
func (mr *MockVoteRepoMockRecorder) FindUserVotes(ctx, userID, targetIDs, targetType interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindUserVotes", reflect.TypeOf((*MockVoteRepo)(nil).FindUserVotes), ctx, userID, targetIDs, targetType)
}

// GetUserVote mocks base method.
func (m *MockVoteRepo) GetUserVote(ctx context.Context, userID, targetID string, targetType model.VoteTargetType) (*model.Vote, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserVote", ctx, userID, targetID, targetType)
	ret0, _ := ret[0].(*model.Vote)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserVote indicates an expected call of GetUserVote.
func (mr *MockVoteRepoMockRecorder) GetUserVote(ctx, userID, targetID, targetType interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserVote", reflect.TypeOf((*MockVoteRepo)(nil).GetUserVote), ctx, userID, targetID, targetType)
}

// RemoveVote mocks base method.
func (m *MockVoteRepo) RemoveVote(ctx context.Context, userID, targetID string, targetType model.VoteTargetType) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveVote", ctx, userID, targetID, targetType)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveVote indicates an expected call of RemoveVote.
func (mr *MockVoteRepoMockRecorder) RemoveVote(ctx, userID, targetID, targetType interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveVote", reflect.TypeOf((*MockVoteRepo)(nil).RemoveVote), ctx, userID, targetID, targetType)
}

// Vote mocks base method.
func (m *MockVoteRepo) Vote(ctx context.Context, userID, targetID string, targetType model.VoteTargetType, voteValue bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Vote", ctx, userID, targetID, targetType, voteValue)
	ret0, _ := ret[0].(error)
	return ret0
}

// Vote indicates an expected call of Vote.
func (mr *MockVoteRepoMockRecorder) Vote(ctx, userID, targetID, targetType, voteValue interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Vote", reflect.TypeOf((*MockVoteRepo)(nil).Vote), ctx, userID, targetID, targetType, voteValue)
}
