// Code generated by MockGen. DO NOT EDIT.
// Source: ../../repo/saved_post_repo.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	model "github.com/giakiet05/lkforum/internal/model"
	repo "github.com/giakiet05/lkforum/internal/repo"
	gomock "github.com/golang/mock/gomock"
	primitive "go.mongodb.org/mongo-driver/bson/primitive"
)

// MockSavedPostRepo is a mock of SavedPostRepo interface.
type MockSavedPostRepo struct {
	ctrl     *gomock.Controller
	recorder *MockSavedPostRepoMockRecorder
}

// MockSavedPostRepoMockRecorder is the mock recorder for MockSavedPostRepo.
type MockSavedPostRepoMockRecorder struct {
	mock *MockSavedPostRepo
}

// NewMockSavedPostRepo creates a new mock instance.
func NewMockSavedPostRepo(ctrl *gomock.Controller) *MockSavedPostRepo {
	mock := &MockSavedPostRepo{ctrl: ctrl}
	mock.recorder = &MockSavedPostRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSavedPostRepo) EXPECT() *MockSavedPostRepoMockRecorder {
	return m.recorder
}

// GetByUserID mocks base method.
func (m *MockSavedPostRepo) GetByUserID(ctx context.Context, userID primitive.ObjectID, findOptions *repo.FindOptions) ([]*model.SavedPost, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByUserID", ctx, userID, findOptions)
	ret0, _ := ret[0].([]*model.SavedPost)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetByUserID indicates an expected call of GetByUserID.
func (mr *MockSavedPostRepoMockRecorder) GetByUserID(ctx, userID, findOptions interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByUserID", reflect.TypeOf((*MockSavedPostRepo)(nil).GetByUserID), ctx, userID, findOptions)
}

// IsSaved mocks base method.
func (m *MockSavedPostRepo) IsSaved(ctx context.Context, userID, postID primitive.ObjectID) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsSaved", ctx, userID, postID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsSaved indicates an expected call of IsSaved.
func (mr *MockSavedPostRepoMockRecorder) IsSaved(ctx, userID, postID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsSaved", reflect.TypeOf((*MockSavedPostRepo)(nil).IsSaved), ctx, userID, postID)
}

// Save mocks base method.
func (m *MockSavedPostRepo) Save(ctx context.Context, userID, postID primitive.ObjectID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, userID, postID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockSavedPostRepoMockRecorder) Save(ctx, userID, postID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockSavedPostRepo)(nil).Save), ctx, userID, postID)
}

// Unsave mocks base method.
func (m *MockSavedPostRepo) Unsave(ctx context.Context, userID, postID primitive.ObjectID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Unsave", ctx, userID, postID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Unsave indicates an expected call of Unsave.
func (mr *MockSavedPostRepoMockRecorder) Unsave(ctx, userID, postID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Unsave", reflect.TypeOf((*MockSavedPostRepo)(nil).Unsave), ctx, userID, postID)
}
