// Code generated by MockGen. DO NOT EDIT.
// Source: ../../repo/draft_repo.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	model "github.com/giakiet05/lkforum/internal/model"
	repo "github.com/giakiet05/lkforum/internal/repo"
	gomock "github.com/golang/mock/gomock"
	primitive "go.mongodb.org/mongo-driver/bson/primitive"
)

// MockDraftRepo is a mock of DraftRepo interface.
type MockDraftRepo struct {
	ctrl     *gomock.Controller
	recorder *MockDraftRepoMockRecorder
}

// MockDraftRepoMockRecorder is the mock recorder for MockDraftRepo.
type MockDraftRepoMockRecorder struct {
	mock *MockDraftRepo
}

// NewMockDraftRepo creates a new mock instance.
func NewMockDraftRepo(ctrl *gomock.Controller) *MockDraftRepo {
	mock := &MockDraftRepo{ctrl: ctrl}
	mock.recorder = &MockDraftRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDraftRepo) EXPECT() *MockDraftRepoMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockDraftRepo) Create(ctx context.Context, draft *model.Draft) (*model.Draft, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, draft)
	ret0, _ := ret[0].(*model.Draft)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockDraftRepoMockRecorder) Create(ctx, draft interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockDraftRepo)(nil).Create), ctx, draft)
}

// Delete mocks base method.
func (m *MockDraftRepo) Delete(ctx context.Context, id primitive.ObjectID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockDraftRepoMockRecorder) Delete(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockDraftRepo)(nil).Delete), ctx, id)
}

// GetByAuthor mocks base method.
func (m *MockDraftRepo) GetByAuthor(ctx context.Context, authorID primitive.ObjectID, opts *repo.FindOptions) ([]*model.Draft, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByAuthor", ctx, authorID, opts)
	ret0, _ := ret[0].([]*model.Draft)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetByAuthor indicates an expected call of GetByAuthor.
func (mr *MockDraftRepoMockRecorder) GetByAuthor(ctx, authorID, opts interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByAuthor", reflect.TypeOf((*MockDraftRepo)(nil).GetByAuthor), ctx, authorID, opts)
}

// GetByID mocks base method.
func (m *MockDraftRepo) GetByID(ctx context.Context, id primitive.ObjectID) (*model.Draft, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*model.Draft)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockDraftRepoMockRecorder) GetByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockDraftRepo)(nil).GetByID), ctx, id)
}

// Update mocks base method.
func (m *MockDraftRepo) Update(ctx context.Context, draft *model.Draft) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, draft)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockDraftRepoMockRecorder) Update(ctx, draft interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockDraftRepo)(nil).Update), ctx, draft)
}
