// Code generated by MockGen. DO NOT EDIT.
// Source: ../../repo/membership_repo.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	model "github.com/giakiet05/lkforum/internal/model"
	gomock "github.com/golang/mock/gomock"
)

// MockMembershipRepo is a mock of MembershipRepo interface.
type MockMembershipRepo struct {
	ctrl     *gomock.Controller
	recorder *MockMembershipRepoMockRecorder
}

// MockMembershipRepoMockRecorder is the mock recorder for MockMembershipRepo.
type MockMembershipRepoMockRecorder struct {
	mock *MockMembershipRepo
}

// NewMockMembershipRepo creates a new mock instance.
func NewMockMembershipRepo(ctrl *gomock.Controller) *MockMembershipRepo {
	mock := &MockMembershipRepo{ctrl: ctrl}
	mock.recorder = &MockMembershipRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMembershipRepo) EXPECT() *MockMembershipRepoMockRecorder {
	return m.recorder
}

// CountMembersByCommunityID mocks base method.
func (m *MockMembershipRepo) CountMembersByCommunityID(ctx context.Context, communityID string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountMembersByCommunityID", ctx, communityID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountMembersByCommunityID indicates an expected call of CountMembersByCommunityID.
func (mr *MockMembershipRepoMockRecorder) CountMembersByCommunityID(ctx, communityID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountMembersByCommunityID", reflect.TypeOf((*MockMembershipRepo)(nil).CountMembersByCommunityID), ctx, communityID)
}

// Create mocks base method.
func (m *MockMembershipRepo) Create(ctx context.Context, membership *model.Membership) (*model.Membership, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, membership)
	ret0, _ := ret[0].(*model.Membership)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockMembershipRepoMockRecorder) Create(ctx, membership interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockMembershipRepo)(nil).Create), ctx, membership)
}

// Delete mocks base method.
func (m *MockMembershipRepo) Delete(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockMembershipRepoMockRecorder) Delete(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockMembershipRepo)(nil).Delete), ctx, id)
}

// GetAllPaginated mocks base method.
func (m *MockMembershipRepo) GetAllPaginated(ctx context.Context, page, pageSize int) ([]*model.Membership, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllPaginated", ctx, page, pageSize)
	ret0, _ := ret[0].([]*model.Membership)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetAllPaginated indicates an expected call of GetAllPaginated.
func (mr *MockMembershipRepoMockRecorder) GetAllPaginated(ctx, page, pageSize interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllPaginated", reflect.TypeOf((*MockMembershipRepo)(nil).GetAllPaginated), ctx, page, pageSize)
}

// GetByCommunityIDPaginated mocks base method.
func (m *MockMembershipRepo) GetByCommunityIDPaginated(ctx context.Context, communityID string, page, pageSize int) ([]*model.Membership, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByCommunityIDPaginated", ctx, communityID, page, pageSize)
	ret0, _ := ret[0].([]*model.Membership)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetByCommunityIDPaginated indicates an expected call of GetByCommunityIDPaginated.
func (mr *MockMembershipRepoMockRecorder) GetByCommunityIDPaginated(ctx, communityID, page, pageSize interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByCommunityIDPaginated", reflect.TypeOf((*MockMembershipRepo)(nil).GetByCommunityIDPaginated), ctx, communityID, page, pageSize)
}

// GetByID mocks base method.
func (m *MockMembershipRepo) GetByID(ctx context.Context, id string) (*model.Membership, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*model.Membership)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockMembershipRepoMockRecorder) GetByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockMembershipRepo)(nil).GetByID), ctx, id)
}

// GetByUserID mocks base method.
func (m *MockMembershipRepo) GetByUserID(ctx context.Context, userID string) ([]*model.Membership, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByUserID", ctx, userID)
	ret0, _ := ret[0].([]*model.Membership)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByUserID indicates an expected call of GetByUserID.
func (mr *MockMembershipRepoMockRecorder) GetByUserID(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByUserID", reflect.TypeOf((*MockMembershipRepo)(nil).GetByUserID), ctx, userID)
}

// IsCommunityExist mocks base method.
func (m *MockMembershipRepo) IsCommunityExist(ctx context.Context, communityID string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsCommunityExist", ctx, communityID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsCommunityExist indicates an expected call of IsCommunityExist.
func (mr *MockMembershipRepoMockRecorder) IsCommunityExist(ctx, communityID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsCommunityExist", reflect.TypeOf((*MockMembershipRepo)(nil).IsCommunityExist), ctx, communityID)
}

// IsMember mocks base method.
func (m *MockMembershipRepo) IsMember(ctx context.Context, userID, communityID string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsMember", ctx, userID, communityID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsMember indicates an expected call of IsMember.
func (mr *MockMembershipRepoMockRecorder) IsMember(ctx, userID, communityID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsMember", reflect.TypeOf((*MockMembershipRepo)(nil).IsMember), ctx, userID, communityID)
}

// IsUserExist mocks base method.
func (m *MockMembershipRepo) IsUserExist(ctx context.Context, userID string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsUserExist", ctx, userID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsUserExist indicates an expected call of IsUserExist.
func (mr *MockMembershipRepoMockRecorder) IsUserExist(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsUserExist", reflect.TypeOf((*MockMembershipRepo)(nil).IsUserExist), ctx, userID)
}

// UpdateCommunityMemberCount mocks base method.
func (m *MockMembershipRepo) UpdateCommunityMemberCount(ctx context.Context, communityID string, count int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCommunityMemberCount", ctx, communityID, count)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateCommunityMemberCount indicates an expected call of UpdateCommunityMemberCount.
func (mr *MockMembershipRepoMockRecorder) UpdateCommunityMemberCount(ctx, communityID, count interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCommunityMemberCount", reflect.TypeOf((*MockMembershipRepo)(nil).UpdateCommunityMemberCount), ctx, communityID, count)
}
