// Code generated by MockGen. DO NOT EDIT.
// Source: ../../repo/post_history_repo.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	model "github.com/giakiet05/lkforum/internal/model"
	gomock "github.com/golang/mock/gomock"
)

// MockPostHistoryRepo is a mock of PostHistoryRepo interface.
type MockPostHistoryRepo struct {
	ctrl     *gomock.Controller
	recorder *MockPostHistoryRepoMockRecorder
}

// MockPostHistoryRepoMockRecorder is the mock recorder for MockPostHistoryRepo.
type MockPostHistoryRepoMockRecorder struct {
	mock *MockPostHistoryRepo
}

// NewMockPostHistoryRepo creates a new mock instance.
func NewMockPostHistoryRepo(ctrl *gomock.Controller) *MockPostHistoryRepo {
	mock := &MockPostHistoryRepo{ctrl: ctrl}
	mock.recorder = &MockPostHistoryRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPostHistoryRepo) EXPECT() *MockPostHistoryRepoMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockPostHistoryRepo) Create(ctx context.Context, postHistory *model.PostHistory) (*model.PostHistory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, postHistory)
	ret0, _ := ret[0].(*model.PostHistory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockPostHistoryRepoMockRecorder) Create(ctx, postHistory interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockPostHistoryRepo)(nil).Create), ctx, postHistory)
}

// CreateBatch mocks base method.
func (m *MockPostHistoryRepo) CreateBatch(ctx context.Context, histories []*model.PostHistory) ([]*model.PostHistory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateBatch", ctx, histories)
	ret0, _ := ret[0].([]*model.PostHistory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateBatch indicates an expected call of CreateBatch.
func (mr *MockPostHistoryRepoMockRecorder) CreateBatch(ctx, histories interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateBatch", reflect.TypeOf((*MockPostHistoryRepo)(nil).CreateBatch), ctx, histories)
}

// DeleteByID mocks base method.
func (m *MockPostHistoryRepo) DeleteByID(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByID", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByID indicates an expected call of DeleteByID.
func (mr *MockPostHistoryRepoMockRecorder) DeleteByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByID", reflect.TypeOf((*MockPostHistoryRepo)(nil).DeleteByID), ctx, id)
}

// GetByID mocks base method.
func (m *MockPostHistoryRepo) GetByID(ctx context.Context, id string) (*model.PostHistory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*model.PostHistory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockPostHistoryRepoMockRecorder) GetByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockPostHistoryRepo)(nil).GetByID), ctx, id)
}

// GetByUserID mocks base method.
func (m *MockPostHistoryRepo) GetByUserID(ctx context.Context, userID string, page, pageSize int) ([]*model.PostHistory, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByUserID", ctx, userID, page, pageSize)
	ret0, _ := ret[0].([]*model.PostHistory)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetByUserID indicates an expected call of GetByUserID.
func (mr *MockPostHistoryRepoMockRecorder) GetByUserID(ctx, userID, page, pageSize interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByUserID", reflect.TypeOf((*MockPostHistoryRepo)(nil).GetByUserID), ctx, userID, page, pageSize)
}
