// Code generated by MockGen. DO NOT EDIT.
// Source: ../../repo/poll_vote_repo.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockPollVoteRepo is a mock of PollVoteRepo interface.
type MockPollVoteRepo struct {
	ctrl     *gomock.Controller
	recorder *MockPollVoteRepoMockRecorder
}

// MockPollVoteRepoMockRecorder is the mock recorder for MockPollVoteRepo.
type MockPollVoteRepoMockRecorder struct {
	mock *MockPollVoteRepo
}

// NewMockPollVoteRepo creates a new mock instance.
func NewMockPollVoteRepo(ctrl *gomock.Controller) *MockPollVoteRepo {
	mock := &MockPollVoteRepo{ctrl: ctrl}
	mock.recorder = &MockPollVoteRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPollVoteRepo) EXPECT() *MockPollVoteRepoMockRecorder {
	return m.recorder
}

// FindUserVotes mocks base method.
func (m *MockPollVoteRepo) FindUserVotes(ctx context.Context, userID string, postIDs []string) (map[string][]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindUserVotes", ctx, userID, postIDs)
	ret0, _ := ret[0].(map[string][]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindUserVotes indicates an expected call of FindUserVotes.
func (mr *MockPollVoteRepoMockRecorder) FindUserVotes(ctx, userID, postIDs interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindUserVotes", reflect.TypeOf((*MockPollVoteRepo)(nil).FindUserVotes), ctx, userID, postIDs)
}

// GetUserVoteIDs mocks base method.
func (m *MockPollVoteRepo) GetUserVoteIDs(ctx context.Context, userID, postID string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserVoteIDs", ctx, userID, postID)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserVoteIDs indicates an expected call of GetUserVoteIDs.
func (mr *MockPollVoteRepoMockRecorder) GetUserVoteIDs(ctx, userID, postID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserVoteIDs", reflect.TypeOf((*MockPollVoteRepo)(nil).GetUserVoteIDs), ctx, userID, postID)
}

// RemoveVote mocks base method.
func (m *MockPollVoteRepo) RemoveVote(ctx context.Context, userID, postID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveVote", ctx, userID, postID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveVote indicates an expected call of RemoveVote.
func (mr *MockPollVoteRepoMockRecorder) RemoveVote(ctx, userID, postID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveVote", reflect.TypeOf((*MockPollVoteRepo)(nil).RemoveVote), ctx, userID, postID)
}

// Vote mocks base method.
func (m *MockPollVoteRepo) Vote(ctx context.Context, userID, postID, optionID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Vote", ctx, userID, postID, optionID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Vote indicates an expected call of Vote.
func (mr *MockPollVoteRepoMockRecorder) Vote(ctx, userID, postID, optionID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Vote", reflect.TypeOf((*MockPollVoteRepo)(nil).Vote), ctx, userID, postID, optionID)
}
