// Code generated by MockGen. DO NOT EDIT.
// Source: ../../repo/community_repo.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	model "github.com/giakiet05/lkforum/internal/model"
	repo "github.com/giakiet05/lkforum/internal/repo"
	gomock "github.com/golang/mock/gomock"
	bson "go.mongodb.org/mongo-driver/bson"
)

// MockCommunityRepo is a mock of CommunityRepo interface.
type MockCommunityRepo struct {
	ctrl     *gomock.Controller
	recorder *MockCommunityRepoMockRecorder
}

// MockCommunityRepoMockRecorder is the mock recorder for MockCommunityRepo.
type MockCommunityRepoMockRecorder struct {
	mock *MockCommunityRepo
}

// NewMockCommunityRepo creates a new mock instance.
func NewMockCommunityRepo(ctrl *gomock.Controller) *MockCommunityRepo {
	mock := &MockCommunityRepo{ctrl: ctrl}
	mock.recorder = &MockCommunityRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCommunityRepo) EXPECT() *MockCommunityRepoMockRecorder {
	return m.recorder
}

// ActivateModerator mocks base method.
func (m *MockCommunityRepo) ActivateModerator(ctx context.Context, communityID, userID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ActivateModerator", ctx, communityID, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// ActivateModerator indicates an expected call of ActivateModerator.
func (mr *MockCommunityRepoMockRecorder) ActivateModerator(ctx, communityID, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ActivateModerator", reflect.TypeOf((*MockCommunityRepo)(nil).ActivateModerator), ctx, communityID, userID)
}

// BanUser mocks base method.
func (m *MockCommunityRepo) BanUser(ctx context.Context, ban *model.CommunityBan) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BanUser", ctx, ban)
	ret0, _ := ret[0].(error)
	return ret0
}

// BanUser indicates an expected call of BanUser.
func (mr *MockCommunityRepoMockRecorder) BanUser(ctx, ban interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BanUser", reflect.TypeOf((*MockCommunityRepo)(nil).BanUser), ctx, ban)
}

// CountActive mocks base method.
func (m *MockCommunityRepo) CountActive(ctx context.Context) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountActive", ctx)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountActive indicates an expected call of CountActive.
func (mr *MockCommunityRepoMockRecorder) CountActive(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountActive", reflect.TypeOf((*MockCommunityRepo)(nil).CountActive), ctx)
}

// CountBanned mocks base method.
func (m *MockCommunityRepo) CountBanned(ctx context.Context) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountBanned", ctx)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountBanned indicates an expected call of CountBanned.
func (mr *MockCommunityRepoMockRecorder) CountBanned(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountBanned", reflect.TypeOf((*MockCommunityRepo)(nil).CountBanned), ctx)
}

// CountCreatedAfter mocks base method.
func (m *MockCommunityRepo) CountCreatedAfter(ctx context.Context, since time.Time) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountCreatedAfter", ctx, since)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountCreatedAfter indicates an expected call of CountCreatedAfter.
func (mr *MockCommunityRepoMockRecorder) CountCreatedAfter(ctx, since interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountCreatedAfter", reflect.TypeOf((*MockCommunityRepo)(nil).CountCreatedAfter), ctx, since)
}

// CountPrivate mocks base method.
func (m *MockCommunityRepo) CountPrivate(ctx context.Context) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountPrivate", ctx)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountPrivate indicates an expected call of CountPrivate.
func (mr *MockCommunityRepoMockRecorder) CountPrivate(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountPrivate", reflect.TypeOf((*MockCommunityRepo)(nil).CountPrivate), ctx)
}

// CountTotal mocks base method.
func (m *MockCommunityRepo) CountTotal(ctx context.Context) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountTotal", ctx)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountTotal indicates an expected call of CountTotal.
func (mr *MockCommunityRepoMockRecorder) CountTotal(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountTotal", reflect.TypeOf((*MockCommunityRepo)(nil).CountTotal), ctx)
}

// Create mocks base method.
func (m *MockCommunityRepo) Create(ctx context.Context, community *model.Community) (*model.Community, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, community)
	ret0, _ := ret[0].(*model.Community)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockCommunityRepoMockRecorder) Create(ctx, community interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockCommunityRepo)(nil).Create), ctx, community)
}

// Delete mocks base method.
func (m *MockCommunityRepo) Delete(ctx context.Context, communityID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, communityID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockCommunityRepoMockRecorder) Delete(ctx, communityID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockCommunityRepo)(nil).Delete), ctx, communityID)
}

// FindCommunities mocks base method.
func (m *MockCommunityRepo) FindCommunities(ctx context.Context, filter repo.Filter, findOptions *repo.FindOptions) ([]*model.Community, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindCommunities", ctx, filter, findOptions)
	ret0, _ := ret[0].([]*model.Community)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// FindCommunities indicates an expected call of FindCommunities.
func (mr *MockCommunityRepoMockRecorder) FindCommunities(ctx, filter, findOptions interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindCommunities", reflect.TypeOf((*MockCommunityRepo)(nil).FindCommunities), ctx, filter, findOptions)
}

// GetAllPaginated mocks base method.
func (m *MockCommunityRepo) GetAllPaginated(ctx context.Context, page, pageSize int) ([]*model.Community, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllPaginated", ctx, page, pageSize)
	ret0, _ := ret[0].([]*model.Community)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetAllPaginated indicates an expected call of GetAllPaginated.
func (mr *MockCommunityRepoMockRecorder) GetAllPaginated(ctx, page, pageSize interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllPaginated", reflect.TypeOf((*MockCommunityRepo)(nil).GetAllPaginated), ctx, page, pageSize)
}

// GetBannedCommunityIDs mocks base method.
func (m *MockCommunityRepo) GetBannedCommunityIDs(ctx context.Context, userID string, banType model.CommunityBanType, communityIDs []string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBannedCommunityIDs", ctx, userID, banType, communityIDs)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBannedCommunityIDs indicates an expected call of GetBannedCommunityIDs.
func (mr *MockCommunityRepoMockRecorder) GetBannedCommunityIDs(ctx, userID, banType, communityIDs interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBannedCommunityIDs", reflect.TypeOf((*MockCommunityRepo)(nil).GetBannedCommunityIDs), ctx, userID, banType, communityIDs)
}

// GetBannedUsers mocks base method.
func (m *MockCommunityRepo) GetBannedUsers(ctx context.Context, communityID string, expired bool) ([]*model.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBannedUsers", ctx, communityID, expired)
	ret0, _ := ret[0].([]*model.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBannedUsers indicates an expected call of GetBannedUsers.
func (mr *MockCommunityRepoMockRecorder) GetBannedUsers(ctx, communityID, expired interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBannedUsers", reflect.TypeOf((*MockCommunityRepo)(nil).GetBannedUsers), ctx, communityID, expired)
}

// GetByID mocks base method.
func (m *MockCommunityRepo) GetByID(ctx context.Context, id string) (*model.Community, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*model.Community)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockCommunityRepoMockRecorder) GetByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockCommunityRepo)(nil).GetByID), ctx, id)
}

// GetByIDs mocks base method.
func (m *MockCommunityRepo) GetByIDs(ctx context.Context, ids []string) ([]*model.Community, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByIDs", ctx, ids)
	ret0, _ := ret[0].([]*model.Community)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByIDs indicates an expected call of GetByIDs.
func (mr *MockCommunityRepoMockRecorder) GetByIDs(ctx, ids interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByIDs", reflect.TypeOf((*MockCommunityRepo)(nil).GetByIDs), ctx, ids)
}

// GetByModeratorIDPaginated mocks base method.
func (m *MockCommunityRepo) GetByModeratorIDPaginated(ctx context.Context, moderatorID string, page, pageSize int) ([]*model.Community, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByModeratorIDPaginated", ctx, moderatorID, page, pageSize)
	ret0, _ := ret[0].([]*model.Community)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetByModeratorIDPaginated indicates an expected call of GetByModeratorIDPaginated.
func (mr *MockCommunityRepoMockRecorder) GetByModeratorIDPaginated(ctx, moderatorID, page, pageSize interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByModeratorIDPaginated", reflect.TypeOf((*MockCommunityRepo)(nil).GetByModeratorIDPaginated), ctx, moderatorID, page, pageSize)
}

// GetByName mocks base method.
func (m *MockCommunityRepo) GetByName(ctx context.Context, name string) (*model.Community, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByName", ctx, name)
	ret0, _ := ret[0].(*model.Community)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByName indicates an expected call of GetByName.
func (mr *MockCommunityRepoMockRecorder) GetByName(ctx, name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByName", reflect.TypeOf((*MockCommunityRepo)(nil).GetByName), ctx, name)
}

// GetFilter mocks base method.
func (m *MockCommunityRepo) GetFilter(ctx context.Context, name, description string, is18Plus bool, createFrom time.Time, page, pageSize int) ([]*model.Community, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFilter", ctx, name, description, is18Plus, createFrom, page, pageSize)
	ret0, _ := ret[0].([]*model.Community)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetFilter indicates an expected call of GetFilter.
func (mr *MockCommunityRepoMockRecorder) GetFilter(ctx, name, description, is18Plus, createFrom, page, pageSize interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFilter", reflect.TypeOf((*MockCommunityRepo)(nil).GetFilter), ctx, name, description, is18Plus, createFrom, page, pageSize)
}

// GetMutedUsers mocks base method.
func (m *MockCommunityRepo) GetMutedUsers(ctx context.Context, communityID string, expired bool) ([]*model.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMutedUsers", ctx, communityID, expired)
	ret0, _ := ret[0].([]*model.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMutedUsers indicates an expected call of GetMutedUsers.
func (mr *MockCommunityRepoMockRecorder) GetMutedUsers(ctx, communityID, expired interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMutedUsers", reflect.TypeOf((*MockCommunityRepo)(nil).GetMutedUsers), ctx, communityID, expired)
}

// IsCreator mocks base method.
func (m *MockCommunityRepo) IsCreator(ctx context.Context, communityID, userID string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsCreator", ctx, communityID, userID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsCreator indicates an expected call of IsCreator.
func (mr *MockCommunityRepoMockRecorder) IsCreator(ctx, communityID, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsCreator", reflect.TypeOf((*MockCommunityRepo)(nil).IsCreator), ctx, communityID, userID)
}

// IsModerator mocks base method.
func (m *MockCommunityRepo) IsModerator(ctx context.Context, communityID, userID string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsModerator", ctx, communityID, userID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsModerator indicates an expected call of IsModerator.
func (mr *MockCommunityRepoMockRecorder) IsModerator(ctx, communityID, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsModerator", reflect.TypeOf((*MockCommunityRepo)(nil).IsModerator), ctx, communityID, userID)
}

// IsUserBanned mocks base method.
func (m *MockCommunityRepo) IsUserBanned(ctx context.Context, userID string, banType model.CommunityBanType, communityID string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsUserBanned", ctx, userID, banType, communityID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsUserBanned indicates an expected call of IsUserBanned.
func (mr *MockCommunityRepoMockRecorder) IsUserBanned(ctx, userID, banType, communityID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsUserBanned", reflect.TypeOf((*MockCommunityRepo)(nil).IsUserBanned), ctx, userID, banType, communityID)
}

// IsUserExist mocks base method.
func (m *MockCommunityRepo) IsUserExist(ctx context.Context, userID string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsUserExist", ctx, userID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsUserExist indicates an expected call of IsUserExist.
func (mr *MockCommunityRepoMockRecorder) IsUserExist(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsUserExist", reflect.TypeOf((*MockCommunityRepo)(nil).IsUserExist), ctx, userID)
}

// Replace mocks base method.
func (m *MockCommunityRepo) Replace(ctx context.Context, community *model.Community) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Replace", ctx, community)
	ret0, _ := ret[0].(error)
	return ret0
}

// Replace indicates an expected call of Replace.
func (mr *MockCommunityRepoMockRecorder) Replace(ctx, community interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Replace", reflect.TypeOf((*MockCommunityRepo)(nil).Replace), ctx, community)
}

// UnbanUser mocks base method.
func (m *MockCommunityRepo) UnbanUser(ctx context.Context, userID, communityID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnbanUser", ctx, userID, communityID)
	ret0, _ := ret[0].(error)
	return ret0
}

// UnbanUser indicates an expected call of UnbanUser.
func (mr *MockCommunityRepoMockRecorder) UnbanUser(ctx, userID, communityID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnbanUser", reflect.TypeOf((*MockCommunityRepo)(nil).UnbanUser), ctx, userID, communityID)
}

// UnmuteUser mocks base method.
func (m *MockCommunityRepo) UnmuteUser(ctx context.Context, userID, communityID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnmuteUser", ctx, userID, communityID)
	ret0, _ := ret[0].(error)
	return ret0
}

// UnmuteUser indicates an expected call of UnmuteUser.
func (mr *MockCommunityRepoMockRecorder) UnmuteUser(ctx, userID, communityID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnmuteUser", reflect.TypeOf((*MockCommunityRepo)(nil).UnmuteUser), ctx, userID, communityID)
}

// Update mocks base method.
func (m *MockCommunityRepo) Update(ctx context.Context, communityID string, updates bson.M) (*model.Community, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, communityID, updates)
	ret0, _ := ret[0].(*model.Community)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockCommunityRepoMockRecorder) Update(ctx, communityID, updates interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockCommunityRepo)(nil).Update), ctx, communityID, updates)
}

// UpdateUserAvatar mocks base method.
func (m *MockCommunityRepo) UpdateUserAvatar(ctx context.Context, userID, newAvatar string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUserAvatar", ctx, userID, newAvatar)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateUserAvatar indicates an expected call of UpdateUserAvatar.
func (mr *MockCommunityRepoMockRecorder) UpdateUserAvatar(ctx, userID, newAvatar interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUserAvatar", reflect.TypeOf((*MockCommunityRepo)(nil).UpdateUserAvatar), ctx, userID, newAvatar)
}
