// Code generated by MockGen. DO NOT EDIT.
// Source: ../../repo/notification_repo.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	model "github.com/giakiet05/lkforum/internal/model"
	gomock "github.com/golang/mock/gomock"
	primitive "go.mongodb.org/mongo-driver/bson/primitive"
)

// MockNotificationRepo is a mock of NotificationRepo interface.
type MockNotificationRepo struct {
	ctrl     *gomock.Controller
	recorder *MockNotificationRepoMockRecorder
}

// MockNotificationRepoMockRecorder is the mock recorder for MockNotificationRepo.
type MockNotificationRepoMockRecorder struct {
	mock *MockNotificationRepo
}

// NewMockNotificationRepo creates a new mock instance.
func NewMockNotificationRepo(ctrl *gomock.Controller) *MockNotificationRepo {
	mock := &MockNotificationRepo{ctrl: ctrl}
	mock.recorder = &MockNotificationRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNotificationRepo) EXPECT() *MockNotificationRepoMockRecorder {
	return m.recorder
}

// CountUnread mocks base method.
func (m *MockNotificationRepo) CountUnread(ctx context.Context, recipientID string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountUnread", ctx, recipientID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountUnread indicates an expected call of CountUnread.
func (mr *MockNotificationRepoMockRecorder) CountUnread(ctx, recipientID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountUnread", reflect.TypeOf((*MockNotificationRepo)(nil).CountUnread), ctx, recipientID)
}

// Create mocks base method.
func (m *MockNotificationRepo) Create(ctx context.Context, notification *model.Notification) (*model.Notification, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, notification)
	ret0, _ := ret[0].(*model.Notification)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockNotificationRepoMockRecorder) Create(ctx, notification interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockNotificationRepo)(nil).Create), ctx, notification)
}

// DeleteNotification mocks base method.
func (m *MockNotificationRepo) DeleteNotification(ctx context.Context, notificationID primitive.ObjectID, recipientID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteNotification", ctx, notificationID, recipientID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteNotification indicates an expected call of DeleteNotification.
func (mr *MockNotificationRepoMockRecorder) DeleteNotification(ctx, notificationID, recipientID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteNotification", reflect.TypeOf((*MockNotificationRepo)(nil).DeleteNotification), ctx, notificationID, recipientID)
}

// GetByRecipientID mocks base method.
func (m *MockNotificationRepo) GetByRecipientID(ctx context.Context, recipientID string, page, pageSize int) ([]*model.Notification, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByRecipientID", ctx, recipientID, page, pageSize)
	ret0, _ := ret[0].([]*model.Notification)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetByRecipientID indicates an expected call of GetByRecipientID.
func (mr *MockNotificationRepoMockRecorder) GetByRecipientID(ctx, recipientID, page, pageSize interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByRecipientID", reflect.TypeOf((*MockNotificationRepo)(nil).GetByRecipientID), ctx, recipientID, page, pageSize)
}

// MarkAllAsRead mocks base method.
func (m *MockNotificationRepo) MarkAllAsRead(ctx context.Context, recipientID string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkAllAsRead", ctx, recipientID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MarkAllAsRead indicates an expected call of MarkAllAsRead.
func (mr *MockNotificationRepoMockRecorder) MarkAllAsRead(ctx, recipientID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkAllAsRead", reflect.TypeOf((*MockNotificationRepo)(nil).MarkAllAsRead), ctx, recipientID)
}

// MarkAsRead mocks base method.
func (m *MockNotificationRepo) MarkAsRead(ctx context.Context, notificationID primitive.ObjectID, recipientID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkAsRead", ctx, notificationID, recipientID)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkAsRead indicates an expected call of MarkAsRead.
func (mr *MockNotificationRepoMockRecorder) MarkAsRead(ctx, notificationID, recipientID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkAsRead", reflect.TypeOf((*MockNotificationRepo)(nil).MarkAsRead), ctx, notificationID, recipientID)
}
