// Code generated by MockGen. DO NOT EDIT.
// Source: ../../repo/email_verification_repo.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	model "github.com/giakiet05/lkforum/internal/model"
	gomock "github.com/golang/mock/gomock"
)

// MockEmailVerificationRepo is a mock of EmailVerificationRepo interface.
type MockEmailVerificationRepo struct {
	ctrl     *gomock.Controller
	recorder *MockEmailVerificationRepoMockRecorder
}

// MockEmailVerificationRepoMockRecorder is the mock recorder for MockEmailVerificationRepo.
type MockEmailVerificationRepoMockRecorder struct {
	mock *MockEmailVerificationRepo
}

// NewMockEmailVerificationRepo creates a new mock instance.
func NewMockEmailVerificationRepo(ctrl *gomock.Controller) *MockEmailVerificationRepo {
	mock := &MockEmailVerificationRepo{ctrl: ctrl}
	mock.recorder = &MockEmailVerificationRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEmailVerificationRepo) EXPECT() *MockEmailVerificationRepoMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockEmailVerificationRepo) Create(ctx context.Context, verification *model.EmailVerification) (*model.EmailVerification, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, verification)
	ret0, _ := ret[0].(*model.EmailVerification)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockEmailVerificationRepoMockRecorder) Create(ctx, verification interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockEmailVerificationRepo)(nil).Create), ctx, verification)
}

// Delete mocks base method.
func (m *MockEmailVerificationRepo) Delete(ctx context.Context, email string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, email)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockEmailVerificationRepoMockRecorder) Delete(ctx, email interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockEmailVerificationRepo)(nil).Delete), ctx, email)
}

// GetByEmail mocks base method.
func (m *MockEmailVerificationRepo) GetByEmail(ctx context.Context, email string) (*model.EmailVerification, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByEmail", ctx, email)
	ret0, _ := ret[0].(*model.EmailVerification)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByEmail indicates an expected call of GetByEmail.
func (mr *MockEmailVerificationRepoMockRecorder) GetByEmail(ctx, email interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByEmail", reflect.TypeOf((*MockEmailVerificationRepo)(nil).GetByEmail), ctx, email)
}

// Update mocks base method.
func (m *MockEmailVerificationRepo) Update(ctx context.Context, verification *model.EmailVerification) (*model.EmailVerification, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, verification)
	ret0, _ := ret[0].(*model.EmailVerification)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockEmailVerificationRepoMockRecorder) Update(ctx, verification interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockEmailVerificationRepo)(nil).Update), ctx, verification)
}
