// Code generated by MockGen. DO NOT EDIT.
// Source: ../../repo/channel_repo.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	model "github.com/giakiet05/lkforum/internal/model"
	gomock "github.com/golang/mock/gomock"
)

// MockChannelRepo is a mock of ChannelRepo interface.
type MockChannelRepo struct {
	ctrl     *gomock.Controller
	recorder *MockChannelRepoMockRecorder
}

// MockChannelRepoMockRecorder is the mock recorder for MockChannelRepo.
type MockChannelRepoMockRecorder struct {
	mock *MockChannelRepo
}

// NewMockChannelRepo creates a new mock instance.
func NewMockChannelRepo(ctrl *gomock.Controller) *MockChannelRepo {
	mock := &MockChannelRepo{ctrl: ctrl}
	mock.recorder = &MockChannelRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockChannelRepo) EXPECT() *MockChannelRepoMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockChannelRepo) Create(ctx context.Context, channel *model.Channel) (*model.Channel, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, channel)
	ret0, _ := ret[0].(*model.Channel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockChannelRepoMockRecorder) Create(ctx, channel interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockChannelRepo)(nil).Create), ctx, channel)
}

// Delete mocks base method.
func (m *MockChannelRepo) Delete(ctx context.Context, channelID, userID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, channelID, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockChannelRepoMockRecorder) Delete(ctx, channelID, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockChannelRepo)(nil).Delete), ctx, channelID, userID)
}

// GetByBothUserID mocks base method.
func (m *MockChannelRepo) GetByBothUserID(ctx context.Context, user1ID, user2ID string) (*model.Channel, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByBothUserID", ctx, user1ID, user2ID)
	ret0, _ := ret[0].(*model.Channel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByBothUserID indicates an expected call of GetByBothUserID.
func (mr *MockChannelRepoMockRecorder) GetByBothUserID(ctx, user1ID, user2ID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByBothUserID", reflect.TypeOf((*MockChannelRepo)(nil).GetByBothUserID), ctx, user1ID, user2ID)
}

// GetByID mocks base method.
func (m *MockChannelRepo) GetByID(ctx context.Context, channelID string) (*model.Channel, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, channelID)
	ret0, _ := ret[0].(*model.Channel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockChannelRepoMockRecorder) GetByID(ctx, channelID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockChannelRepo)(nil).GetByID), ctx, channelID)
}

// GetByUserID mocks base method.
func (m *MockChannelRepo) GetByUserID(ctx context.Context, userID string, page, pageSize int) ([]model.Channel, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByUserID", ctx, userID, page, pageSize)
	ret0, _ := ret[0].([]model.Channel)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetByUserID indicates an expected call of GetByUserID.
func (mr *MockChannelRepoMockRecorder) GetByUserID(ctx, userID, page, pageSize interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByUserID", reflect.TypeOf((*MockChannelRepo)(nil).GetByUserID), ctx, userID, page, pageSize)
}

// IsMember mocks base method.
func (m *MockChannelRepo) IsMember(ctx context.Context, channelID, userID string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsMember", ctx, channelID, userID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsMember indicates an expected call of IsMember.
func (mr *MockChannelRepoMockRecorder) IsMember(ctx, channelID, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsMember", reflect.TypeOf((*MockChannelRepo)(nil).IsMember), ctx, channelID, userID)
}

// Update mocks base method.
func (m *MockChannelRepo) Update(ctx context.Context, channel *model.Channel) (*model.Channel, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, channel)
	ret0, _ := ret[0].(*model.Channel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockChannelRepoMockRecorder) Update(ctx, channel interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockChannelRepo)(nil).Update), ctx, channel)
}

// UpdateUserAvatar mocks base method.
func (m *MockChannelRepo) UpdateUserAvatar(ctx context.Context, userID, newAvatar string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUserAvatar", ctx, userID, newAvatar)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateUserAvatar indicates an expected call of UpdateUserAvatar.
func (mr *MockChannelRepoMockRecorder) UpdateUserAvatar(ctx, userID, newAvatar interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUserAvatar", reflect.TypeOf((*MockChannelRepo)(nil).UpdateUserAvatar), ctx, userID, newAvatar)
}
