// Code generated by MockGen. DO NOT EDIT.
// Source: ../../repo/comment_repo.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	model "github.com/giakiet05/lkforum/internal/model"
	gomock "github.com/golang/mock/gomock"
	bson "go.mongodb.org/mongo-driver/bson"
)

// MockCommentRepo is a mock of CommentRepo interface.
type MockCommentRepo struct {
	ctrl     *gomock.Controller
	recorder *MockCommentRepoMockRecorder
}

// MockCommentRepoMockRecorder is the mock recorder for MockCommentRepo.
type MockCommentRepoMockRecorder struct {
	mock *MockCommentRepo
}

// NewMockCommentRepo creates a new mock instance.
func NewMockCommentRepo(ctrl *gomock.Controller) *MockCommentRepo {
	mock := &MockCommentRepo{ctrl: ctrl}
	mock.recorder = &MockCommentRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCommentRepo) EXPECT() *MockCommentRepoMockRecorder {
	return m.recorder
}

// CountCreatedAfter mocks base method.
func (m *MockCommentRepo) CountCreatedAfter(ctx context.Context, since time.Time) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountCreatedAfter", ctx, since)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountCreatedAfter indicates an expected call of CountCreatedAfter.
func (mr *MockCommentRepoMockRecorder) CountCreatedAfter(ctx, since interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountCreatedAfter", reflect.TypeOf((*MockCommentRepo)(nil).CountCreatedAfter), ctx, since)
}

// CountTotal mocks base method.
func (m *MockCommentRepo) CountTotal(ctx context.Context) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountTotal", ctx)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountTotal indicates an expected call of CountTotal.
func (mr *MockCommentRepoMockRecorder) CountTotal(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountTotal", reflect.TypeOf((*MockCommentRepo)(nil).CountTotal), ctx)
}

// Create mocks base method.
func (m *MockCommentRepo) Create(ctx context.Context, comment *model.Comment) (*model.Comment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, comment)
	ret0, _ := ret[0].(*model.Comment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockCommentRepoMockRecorder) Create(ctx, comment interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockCommentRepo)(nil).Create), ctx, comment)
}

// Delete mocks base method.
func (m *MockCommentRepo) Delete(ctx context.Context, commentID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, commentID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockCommentRepoMockRecorder) Delete(ctx, commentID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockCommentRepo)(nil).Delete), ctx, commentID)
}

// GetAllChildren mocks base method.
func (m *MockCommentRepo) GetAllChildren(ctx context.Context, commentID string) ([]model.Comment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllChildren", ctx, commentID)
	ret0, _ := ret[0].([]model.Comment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllChildren indicates an expected call of GetAllChildren.
func (mr *MockCommentRepoMockRecorder) GetAllChildren(ctx, commentID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllChildren", reflect.TypeOf((*MockCommentRepo)(nil).GetAllChildren), ctx, commentID)
}

// GetByID mocks base method.
func (m *MockCommentRepo) GetByID(ctx context.Context, commentID string) (*model.Comment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, commentID)
	ret0, _ := ret[0].(*model.Comment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockCommentRepoMockRecorder) GetByID(ctx, commentID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockCommentRepo)(nil).GetByID), ctx, commentID)
}

// GetByParentIDsPaginated mocks base method.
func (m *MockCommentRepo) GetByParentIDsPaginated(ctx context.Context, parentIDs []string, page, pageSize int) ([]model.Comment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByParentIDsPaginated", ctx, parentIDs, page, pageSize)
	ret0, _ := ret[0].([]model.Comment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByParentIDsPaginated indicates an expected call of GetByParentIDsPaginated.
func (mr *MockCommentRepoMockRecorder) GetByParentIDsPaginated(ctx, parentIDs, page, pageSize interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByParentIDsPaginated", reflect.TypeOf((*MockCommentRepo)(nil).GetByParentIDsPaginated), ctx, parentIDs, page, pageSize)
}

// GetCommentsFilterPaginated mocks base method.
func (m *MockCommentRepo) GetCommentsFilterPaginated(ctx context.Context, postID, parentID, userID, content, currentUserID *string, page, pageSize int) ([]model.Comment, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCommentsFilterPaginated", ctx, postID, parentID, userID, content, currentUserID, page, pageSize)
	ret0, _ := ret[0].([]model.Comment)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetCommentsFilterPaginated indicates an expected call of GetCommentsFilterPaginated.
func (mr *MockCommentRepoMockRecorder) GetCommentsFilterPaginated(ctx, postID, parentID, userID, content, currentUserID, page, pageSize interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCommentsFilterPaginated", reflect.TypeOf((*MockCommentRepo)(nil).GetCommentsFilterPaginated), ctx, postID, parentID, userID, content, currentUserID, page, pageSize)
}

// UpdateByID mocks base method.
func (m *MockCommentRepo) UpdateByID(ctx context.Context, commentID string, update bson.M) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateByID", ctx, commentID, update)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateByID indicates an expected call of UpdateByID.
func (mr *MockCommentRepoMockRecorder) UpdateByID(ctx, commentID, update interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateByID", reflect.TypeOf((*MockCommentRepo)(nil).UpdateByID), ctx, commentID, update)
}
